# Lattice lcmxo256 MachXO FPGA, in 100-pin TQFP package
fpga = Component(
    footprint="Housings_QFP:TQFP-100_14x14mm_Pitch0.5mm",  # 14x14mm 100-pin TQFP
    identifier="U?",
    value="LCMXO256",
    pins=[
        Pin(  1, "PL2A", [""]),
        Pin(  2, "PL2B", [""]),
        Pin(  3, "PL3A", [""]),
        Pin(  4, "PL3B", [""]),
        Pin(  5, "PL3C", [""]),
        Pin(  6, "PL3D", [""]),
        Pin(  7, "PL4A", [""]),
        Pin(  8, "PL4B", [""]),
        Pin(  9, "PL5A", [""]),
        Pin( 10, "VCCIO1", ["3V3"]),
        Pin( 11, "PL5B", [""]),
        Pin( 12, "GNDIO1", ["GND"]),
        Pin( 13, "PL5C", [""]),
        Pin( 14, "PL5D_GSRN", [""]),
        Pin( 15, "PL6A", [""]),
        Pin( 16, "PL6B_TSALL", [""]),
        Pin( 17, "PL7A", [""]),
        Pin( 18, "PL7B", [""]),
        Pin( 19, "PL7C", [""]),
        Pin( 20, "PL7D", [""]),
        Pin( 21, "PL8A", [""]),
        Pin( 22, "PL8B", [""]),
        Pin( 23, "PL9A", [""]),
        Pin( 24, "VCCIO1", ["3V3"]),
        Pin( 25, "GNDIO1", ["GND"]),
        Pin( 26, "TMS", ["TMS"]),  # has an internal pull-up resistor
        Pin( 27, "PL9B", [""]),
        Pin( 28, "TCK", ["TCK"]),  # needs external 4k7 pull-DOWN resistor
        Pin( 29, "PB2A", [""]),
        Pin( 30, "PB2B", [""]),
        Pin( 31, "TDO", ["TDO"]),  # has an internal pull-up resistor
        Pin( 32, "PB2C", [""]),
        Pin( 33, "TDI", ["TDI"]),  # has an internal pull-up resistor
        Pin( 34, "PB2D", [""]),
        Pin( 35, "VCC", ["3V3"]),
        Pin( 36, "PB3A_PCLK1_1", [""]),
        Pin( 37, "PB3B", [""]),
        Pin( 38, "PB3C_PCLK1_0", [""]),
        Pin( 39, "PB3D", [""]),
        Pin( 40, "GND", ["GND"]),
        Pin( 41, "VCCIO1", ["3V3"]),
        Pin( 42, "GNDIO1", ["GND"]),
        Pin( 43, "PB4A", [""]),
        Pin( 44, "PB4B", [""]),
        Pin( 45, "PB4C", [""]),
        Pin( 46, "PB4D", [""]),
        Pin( 47, "PB5A", [""]),
        Pin( 48, "SLEEPN", ["SLEEPN"]),  # needs external 4k7 pull-up resistor
        Pin( 49, "PB5C", [""]),
        Pin( 50, "PB5D", [""]),
        Pin( 51, "PR9B", [""]),
        Pin( 52, "PR9A", [""]),
        Pin( 53, "PR8B", [""]),
        Pin( 54, "PR8A", [""]),
        Pin( 55, "PR7D", [""]),
        Pin( 56, "PR7C", [""]),
        Pin( 57, "PR7B", [""]),
        Pin( 58, "PR7A", [""]),
        Pin( 59, "PR6B", [""]),
        Pin( 60, "VCCIO0", ["3V3"]),
        Pin( 61, "PR6A", [""]),
        Pin( 62, "GNDIO0", ["GND"]),
        Pin( 63, "PR5D", [""]),
        Pin( 64, "PR5C", [""]),
        Pin( 65, "PR5B", [""]),
        Pin( 66, "PR5A", [""]),
        Pin( 67, "PR4B", [""]),
        Pin( 68, "PR4A", [""]),
        Pin( 69, "PR3D", [""]),
        Pin( 70, "PR3C", [""]),
        Pin( 71, "PR3B", [""]),
        Pin( 72, "PR3A", [""]),
        Pin( 73, "PR2B", [""]),
        Pin( 74, "VCCIO0", ["3V3"]),
        Pin( 75, "GNDIO0", ["GND"]),
        Pin( 76, "PR2A", [""]),
        Pin( 77, "PT5C", [""]),
        Pin( 78, "PT5B", [""]),
        Pin( 79, "PT5A", [""]),
        Pin( 80, "PT4F", [""]),
        Pin( 81, "PT4E", [""]),
        Pin( 82, "PT4D", [""]),
        Pin( 83, "PT4C", [""]),
        Pin( 84, "GND", ["GND"]),
        Pin( 85, "PT4B_PCLK0_1", [""]),
        Pin( 86, "PT4A_PCLK0_0", [""]),
        Pin( 87, "PT3D", [""]),
        Pin( 88, "VCCAUX", ["3V3"]),
        Pin( 89, "PT3C", [""]),
        Pin( 90, "VCC", ["3V3"]),
        Pin( 91, "PT3B", ["GND"]),
        Pin( 92, "VCCIO0", [""]),
        Pin( 93, "GNDIO0", [""]),
        Pin( 94, "PT3A", [""]),
        Pin( 95, "PT2F", [""]),
        Pin( 96, "PT2E", [""]),
        Pin( 97, "PT2D", [""]),
        Pin( 98, "PT2C", [""]),
        Pin( 99, "PT2B", [""]),
        Pin(100, "PT2A", [""]),
    ],
)
machxo_sleepn_pullup = myelin_kicad_pcb.R0805("4k7", "SLEEPN", "3V3", ref="R?")
machxo_tck_pulldown = myelin_kicad_pcb.R0805("4k7", "TCK", "GND", ref="R?")
